version: '3'
services:
  app-mysql:
    container_name: mysql-db
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: medidrone
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always

  app-medidrone:
    container_name: medidrone
    image: arunit9/medidrone
    restart: on-failure
    ports:
    - "8080:8080"
    - "8000:8000"
    depends_on:
    - app-mysql
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=medidrone
      - DATABASE_PORT=3306
      - AUDIT_DB_ENABLE=true
      - AUDIT_PERIOD=20000
      - SERVER_LOG_LEVEL=INFO
      - SHOW_VALIDATIONS_ERRORS=always